= Cahier De Recette de l'application Belote
:toc:
:toclevels: 3
:toc-title: Sommaire

Groupe *Oui* (2A) : Hugo WENDJANEH et Tilian HURÉ

{empty} +

== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre du refactoring de l'application de gestion de matchs de Belote dans le contexte de la SAE 4.01. Ce document spécifie l'ensemble des cas testés pour l'application Java.

{empty} +

== II. Pre-Requis :
[.text-justify]
L'exécution des tests requiert :

* Le répertoire `Belote` avec le code source réfactoré de l'application
* Le fichier `RUNAPP.bat` (à configurer) pour lancer l'application sous Windows
* Le fichier `RUNAPP.sh` (à configurer) pour lancer l'application sous Linux

=== 1. Environnement de test :
[.text-justify]
Un poste avec le système d'exploitation *Windows* ou *Linux*, un environnement Java (au moins la version 17.x.x) et l'outil de production https://maven.apache.org/[Maven].

=== 2. Lancement de l'application :
[.text-justify]
Pour lancer facilement et correctement l'application avec Maven sous Windows ou Linux, des fichiers `RUNAPP.bat` et `RUNAPP.sh` sont fournis avec le code source. Ces derniers nécessitent d'avoir préalablement préparé l'environnement d'exécution comme spécifié plus haut.

* Sous Windows, ouvrir simplement le fichier `RUNAPP.bat`
* Sous Linux, se placer dans le répertoire du fichier `RUNAPP.sh` puis exécuter la commande `sh RUNAPP.sh` dans un terminal

=== 3. Éléments à tester :
[.text-justify]
Les éléments testés concernent :

* La CRUD des tournois
* Le CRUD et la validation des équipes
* L'ajout et la suppression des tours d'une partie
* La saisie des scores d'un match
* Les résultats d'une partie

NOTE: CRUD : Fonctionnalités de gestion de base (Create, Read, Update, Delete)

{empty} +

== III. Cas de test :
=== 1. CRUD des tournois :
==== 1.1) Ajout d'un tournoi :

|====

>|Cas de test 3+|Test-01-01-01
>|Titre 3+|Ajout d'un nouveau tournoi
>|Objectif 3+| Vérifier qu'il est possible d'ajouter un nouveau tournoi

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Créer un tournoi"^|Affiche un champ de saisie du nom du tournoi ^|OK
^|2 ^|Saisir un nom de tournoi et cliquer sur "OK" ^|Ferme le champ et ajoute le tournoi ^|OK

|====

|====

>|Cas de test 3+|Test-01-01-01
>|Titre 3+|Ajout d'un nouveau tournoi existant
>|Objectif 3+| Vérifier qu'il est n'est pas possible d'ajouter un tournoi dont le nom existe déjà

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur le bouton "Créer un tournoi"^|Affiche un champ de saisie du nom du tournoi ^|OK
^|2 ^|Saisir un nom de tournoi déjà existant et cliquer sur "OK" ^|Affiche un message d'erreur clair ^|OK

|====

==== 1.2) Suppression d'un tournoi :

|====

>|Cas de test 3+|Test-01-02-01
>|Titre 3+|Suppression d'un tournoi
>|Objectif 3+| Vérifier qu'il est possible de supprimer un tournoi

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Sélectionner le tournoi à supprimer et cliquer sur "Supprimer le tournoi"^|Supprime le tournoi sélectionné ^|OK

|====

==== 1.3) Consulter/continuer un tournoi :
[underline]#Nécessite d'avoir créé et sélectionné un tournoi.#

|====

>|Cas de test 3+|Test-01-01-01
>|Titre 3+|Activation des boutons de consultation/continuation d'un tournoi
>|Objectif 3+| Vérifier que les boutons sur la gauche de l'interface ne sont pas activés tant qu'un tournoi n'est pas sélectionné

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Aucun tournoi sélectionné^|Désactivation de tous les boutons sur la gauche de l'interface (sauf "Tournois") ^|OK
^|2 ^|Sélection d'un tournoi ^|Activation des boutons (au minimum "Paramètres" et "Equipes") ^|OK

|====

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Consultation des données d'un tournoi
>|Objectif 3+| Vérifier qu'il est possible d'accéder à une page détaillant les données de paramétrage d'un tournoi

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Sélectionner un tournoi et cliquer sur "Paramètres"  ^|Affichage d'une fenêtre avec les données de paramètrage d'un tournoi ^|OK

|====

=== 2. CRUD des équipes :
[underline]#Nécessite d'avoir créé et sélectionné un tournoi.#

==== 2.1) Consultation des équipes :

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Consultation des données des équipes d'un tournoi
>|Objectif 3+| Vérifier qu'il est possible d'accéder à une page permettant la gestion des équipes d'un tournoi

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Sélectionner un tournoi et cliquer sur "Equipes"  ^|Affichage d'une fenêtre de gestion des équipes ^|OK

|====

==== 2.2) Saisie des équipes :

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Ajout d'un nombre pair d'équipes d'un tournoi
>|Objectif 3+| Vérifier que le bouton "Valider les équipes" ne s'active que lorsque le nombre d'équipes ajoutées est pair

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Ajouter un nombre impair d'équipes avec le bouton "Ajouter une équipe"  ^|Désactivation du bouton "Valider les équipes" ^|OK
^|2 ^|Ajouter un nombre pair d'équipes ^|Activation du bouton "Valider les équipes" ^|OK

|====

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Modification des noms des joueurs des équipes
>|Objectif 3+| Vérifier qu'il est possible de modifier les noms des joueurs d'une équipe

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Ne pas saisir de nouveaux noms pour des joueurs ^|Les noms saisis par défaut sont "Joueur 1" et "Joueur 2" ^|OK
^|2 ^|Saisir un champ vide pour le nom d'un joueur  ^|Affichage d'un message d'erreur clair ^|*PAS OK* : le champ vide est quand même pris en compte
^|3 ^|Saisir un nouveau nom pour un joueur ^|Modification du nom du joueur ^|OK

|====

==== 2.3) Suppression d'une équipe
[underline]#Nécessite d'avoir créé et sélectionné une équipe.#

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Suppression d'une équipe
>|Objectif 3+| Vérifier qu'il est possible de supprimer une équipe sélectionnée

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Sélectionner une équipe et cliquer sur "Supprimer une équipe" ^|Suppression de l'équipe sélectionnée ^|OK

|====

==== 2.4) Validation des équipes
[underline]#Nécessite d'avoir créé un nombre pair d'équipes.#

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Valider des équipes
>|Objectif 3+| Vérifier qu'il est possible de valider des équipes, rendant leur modification impossible par la suite

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Cliquer sur "Valider les équipes" ^|Validation des équipes ^|OK
^|2 ^|Cliquer sur "Valider les équipes" ^|Activation des boutons "Tours et Matchs" sur la gauche de l'interface ^|OK
^|1 ^|Cliquer sur "Valider les équipes" ^|Désactivation de la modification des équipes ^|OK

|====

=== 3. Gestion des tours d'une partie
[underline]#Nécessite d'avoir validé les équipes d'un tournoi.#

==== 3.1) Consultation des tours :

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Consultation des données des tours d'une partie
>|Objectif 3+| Vérifier qu'il est possible d'accéder à une page permettant de consulter les données des tours d'une partie (numéro des tours, nombre de matchs, parties jouées, etc)

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Valider les équipes d'un tournoi et cliquer sur "Tours"  ^|Affichage d'une fenêtre avec les données correspondantes ^|OK

|====

==== 3.2) Ajout d'un tour :

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Ajout d'un tour
>|Objectif 3+| Vérifier qu'il est possible d'ajouter un tour si les tous les matchs du tour précédent sont terminés

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Les données du match précédent n'ont pas été saisies  ^|Désactivation du bouton "Ajouter un tour" ^|OK
^|1 ^|Saisir les données du match précédent et cliquer sur "Ajouter un tour"  ^|Ajout d'un nouveau tour et de nouveaux matchs à saisir ^|OK

|====

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Ajout d'un tour
>|Objectif 3+| Vérifier qu'il est possible d'ajouter un tour si le nombre de tour est inférieur au nombre d'équipes - 1

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Le nombre de tours est inférieur au nombre d'équipes - 1 ^|Activation du bouton "Ajouter un tour" ^|OK
^|1 ^|Le nombre de tours est égal au nombre d'équipes - 1  ^|Désactivation du bouton "Ajouter un tour" ^|OK

|====

==== 3.3) Suppression du dernier tour :
[underline]#Nécessite d'avoir au moins ajouté deux tours.#

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Ajout d'un tour
>|Objectif 3+| Vérifier qu'il est possible de supprimer le dernier tour d'une partie

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Le nombre de tours est inférieur à 2 ^|Le bouton "Supprimer le dernier tour" est désactivé ^|OK
^|1 ^|Ajouter au moins deux tours et cliquer sur le bouton "Supprimer le dernier tour"  ^|Suppression du dernier tour ^|OK

|====

=== 4. Consultation et saisie des données d'un match
[underline]#Nécessite d'avoir validé les équipes d'un tournoi.#

==== 4.1) Consultation des matchs :

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Consultation des données des matchs d'une partie
>|Objectif 3+| Vérifier qu'il est possible d'accéder à une page permettant de saisir les données des derniers matchs d'un tour

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Valider les équipes d'un tournoi et cliquer sur "Matchs"  ^|Affichage d'une fenêtre avec les champs des scores à compléter pour les matchs correspondants ^|OK

|====

==== 4.2) Saisie des scores d'un match

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Ajout d'un tour
>|Objectif 3+| Vérifier qu'il est possible de saisir les scores derniers matchs d'un tour

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir les scores des derniers matchs d'un tour ^|Activation du bouton "Résultats" sur la gauche de l'interface ^|OK

|====

=== 5. Consultation des résultats d'une partie
[underline]#Nécessite d'avoir saisie les scores des matchs d'au moins un tour.#

==== 5.1) Consultation des résultats d'un tournoi :

|====

>|Cas de test 3+|Test-01-03-01
>|Titre 3+|Consultation des résultats des matchs d'une partie
>|Objectif 3+| Vérifier qu'il est possible d'accéder à une page permettant de visualiser les résultats des matchs d'un tournoi

4+|

^|ID ^|Action ^|Comportement attendu ^|Résultat
^|1 ^|Saisir les scores des matchs d'au moins un tour et cliquer sur "Matchs"  ^|Affichage d'une fenêtre avec les résultats calculés pour chaque équipe ^|(en partie) OK : bug avec l'affichage des noms des joueurs des équipes

|====